### ISSUE TITLE
Tracking Issue: Migrate Helper Plugin to TypeScript

### ISSUE THREAD

**Issue by markkaylor** [strapi/strapi#17690]
Internally we will begin migrating the helper-plugin to TypeScript. If you would like to contribute please comment which file(s) you would like to work on and we will add you to the list. 

### Contributing

If you aren't sure how to get started please checkout our Contributing guide: https://contributor.strapi.io/guides/contributing

- Pull requests must be based off of and target https://github.com/strapi/strapi/tree/chore/ts-migrate-helper-plugin
- Pull requests must provide relevant unit tests
- Pull requests should contain the migration work for a single file
- Pull requests should reference this issue

If a function is no longer used in the Strapi codebase, please mark it as deprecated using JSDoc @deprecated and suggest a replacement.

Please use `git mv` to maintain the git history, for example:

```
git mv <path-to-file>/some-file.js <path-to-file>/some-file.ts
```

To use types from the design system you will need a local copy of [the design system](https://github.com/strapi/design-system) to generate the types manually:
- Run `DTS=true yarn build` 
- Follow the steps to [yarn link the design system to the monorepo](https://contributor.strapi.io/guides/working-with-the-design-system)

---

**Progress tracking**

33% on 31.08
51% on 05.09
63% on 08.09
65% on 11.09
100% on 13.09

## Utils - 100% done  - 20/20

- [x]  auth.js - @markkaylor 
- [x]  awaitToJs.js @fletch-r 
- [x]  difference.js - @joshuaellis
- [x]  fetchClient.js @Feranchz 
- [x]  getAPIInnerErrors.js @Feranchz 
- [x]  getFetchClient.js @Feranchz 
- [x]  getFileExtension.js @fletch-r
- [x]  getPrefixedId.js @fletch-r
- [x]  getYupInnerErrors.js @Feranchz 
- [x]  hasPermissions.js - @joshuaellis 
- [x]  normalizeAPIError.js @Feranchz 
- [x]  once.js - @BorysShulyak 
- [x]  prefixFileUrlWithBackendUrl.js - @BorysShulyak
- [x]  prefixPluginTranslations.js - @BorysShulyak
- [x]  pxToRem.js @madhurisandbhor 
- [x]  request.js @remidej
- [x]  setHexOpacity.js - @fletch-r
- [x]  stopPropagation.js @remidej
- [x]  translatedErrors.js @remidej
- [x]  wrapAxiosInstance.js @remidej

## Icons - 100% done - 2/2

- [x]  RemoveRoundedButton.jsx - @madhurisandbhor 
- [x]  SortIcon.jsx @madhurisandbhor 

## Hooks - 100% done - 14/14

- [x]  useAPIErrorHandler.js - @joshuaellis 
- [x]  useCallbackRef.js - @rortan134 
- [x]  useClipboard.js - @jbhammon 
- [x]  useFetchClient.js - @madhurisandbhor 
- [x]  useFieldHint.js @Feranchz 
- [x]  useFilter.js @Feranchz 
- [x]  useFocusWhenNavigate.js @yurimutti 
- [x]  useFormattedMessage.js @yurimutti 
- [x]  useLockScroll.js @yurimutti 
- [x]  usePersistentState.js - @madhurisandbhor 
- [x]  useQuery.js - @joshuaellis  
- [x]  useQueryParams.js - @madhurisandbhor 
- [x]  useRBAC.js - @madhurisandbhor 
- [x]  useSelectionState.js - @madhurisandbhor 

## Features - 100% done - 10/10

- [x] AppInfo.jsx @fletch-r
- [x] AutoReloadOverlayBlocker.jsx @Feranchz 
- [x] CustomFields.jsx - @markkaylor 
- [x] GuidedTour.jsx - @markkaylor 
- [x] Library.jsx @Feranchz 
- [x] Notifications.jsx @joshuaellis 
- [x] OverlayBlocker.jsx @Feranchz 
- [x] RBAC.jsx @madhurisandbhor 
- [x] StrapiApp.jsx - @markkaylor 
- [x] Tracking.jsx @joshuaellis 

## Components - 100% done - 29/29

- [x] AnErrorOccurred.jsx - @nolliebigspin 
- [x] CheckPagePermissions.jsx - @Feranchz 
- [x] CheckPermissions.jsx - @Feranchz 
- [x] ConfirmDialog.jsx - @mkcy3 
- [x] ContentBox.jsx - @mkcy3 
- [x] DateTimePicker.jsx - @Feranchz 
- [x] DynamicTable.jsx - @Feranchz 
- [x] EmptyBodyTable.jsx - @Feranchz 
- [x] EmptyStateLayout.jsx - @Feranchz 
- [x] FilterListURLQuery.jsx - @simotae14 
- [x] FilterPopoverURLQuery.jsx @joshuaellis
- [x] Form.jsx - @Tegacreatives 
- [x] GenericInput.jsx - @markkaylor 
- [x] InjectionZone.jsx - @joshuaellis 
- [x] Link.jsx - @dallasclark 
- [x] LinkButton.jsx - @dallasclark 
- [x] LoadingIndicatorPage.jsx - @yurimutti 
- [x] NoContent.jsx - @nolliebigspin 
- [x] NoMedia.jsx - @dallasclark 
- [x] NoPermissions.jsx - @nolliebigspin 
- [x] NotAllowedInput.jsx - @dallasclark 
- [x] PageSizeURLQuery.jsx - @Feranchz 
- [x] PaginationURLQuery.jsx - @JuliusGudni 
- [x] ReactSelect.jsx - @JuliusGudni 
- [x] RelativeTime.jsx - @JuliusGudni 
- [x] SearchURLQuery.jsx - @simotae14 
- [x] SettingsPageTitle.jsx - @yurimutti 
- [x] Status.jsx @dallasclark 
- [x] Table.jsx - @joshuaellis 

### Contexts - 100% done - 1/1
- [x] ContentManagerEditViewDataManagerContext.jsx @joshuaellis 

### Hooks - 100% done - 1/1
- [x] useCMEditViewDataManager.js @joshuaellis 

### Utils - 100% done - 3/3
- [x] contentManagementUtilRemoveFieldsFromData.js @joshuaellis
- [x] formatContentTypeData.js - @joshuaellis
- [x] getAttributeInfos.js @fletch-r

**Comment by derrickmehaffy** [comment]
@ComfortablyCoding This one is for you :) Since you asked me about helping out with some TS stuff.

**Comment by rortan134** [comment]
I can work on a few hooks

Assign me the first two :)

**Comment by dallasclark** [comment]
Nice, this is a great way to get started.

* Do you have a gold example of a converted file?
* Are we going to have gradual typing or going with a big bang approach?

I'm happy to grab the smallest / easiest to begin with and work out the expectations to apply with others.

**Comment by ilyas-muhammad** [comment]
Very nice things to get started!

Please assign me a task from the first Utils section.

**Comment by mkcy3** [comment]
ContentBox.jsx

**Comment by madhurisandbhor** [comment]
Hooks: 
 usePersistentState.js
 useQuery.js
 useQueryParams.js
 useRBAC.js
 useSelectionState.js

**Comment by nolliebigspin** [comment]
Nice!
I'd like to do my first contributions here.

Please assign be to some simple components. For example:
- AnErrorOccurred.jsx
- NoContent.jsx
- NoPermissions.jsx

**Comment by markkaylor** [comment]
> Nice, this is a great way to get started.
> 
> * Do you have a gold example of a converted file?
> * Are we going to have gradual typing or going with a big bang approach?
> 
> I'm happy to grab the smallest / easiest to begin with and work out the expectations to apply with others.

Hey @dallasclark to give you an idea of what we are going for you could take a look at the [design system](https://github.com/strapi/design-system) which has already been migrated to TypeScript

**Comment by markkaylor** [comment]
> Very nice things to get started!
> 
> Please assign me a task from the first Utils section.

Hi @ilyas-muhammad thanks for your interest in contributing! Do you mind naming the file(s) you would be willing to work on?

**Comment by ilyas-muhammad** [comment]
> > Very nice things to get started!
> > Please assign me a task from the first Utils section.
> 
> Hi @ilyas-muhammad thanks for your interest in contributing! Do you mind naming the file(s) you would be willing to work on?

Hi @markkaylor : I am more than happy to start with `difference.js`

**Comment by jbhammon** [comment]
I'm happy to help as well, assign me the next two unassigned hooks as a starting point.

Would the team like one PR per file, or are larger groups of changes alright here?

**Comment by markkaylor** [comment]
> Would the team like one PR per file, or are larger groups of changes alright here?

Good question. I think 1 PR per file would be best.

**Comment by julesgabriel** [comment]
Hello !  fetchClient.js please

**Comment by yurimutti** [comment]
Please assign to me:

Hooks:
useLockScroll.js
useFormattedMessage.js
useFocusWhenNavigate.js

Components:
LoadingIndicatorPage.jsx
Status.jsx
SettingsPageTitle.jsx

**Comment by dallasclark** [comment]
> Please assign to me:
> 
> Hooks: useLockScroll.js useFormattedMessage.js useFocusWhenNavigate.js
> 
> Components: LoadingIndicatorPage.jsx Status.jsx SettingsPageTitle.jsx

Do you mind if I take `Status.jsx` as a warm-up?

**Comment by yurimutti** [comment]
> > Please assign to me:
> > Hooks: useLockScroll.js useFormattedMessage.js useFocusWhenNavigate.js
> > Components: LoadingIndicatorPage.jsx Status.jsx SettingsPageTitle.jsx
> 
> Do you mind if I take `Status.jsx` as a warm-up?

No problem.

**Comment by bogdaaamn** [comment]
hey! would love to start with `hasPermissions.js` and `EmptyBodyTable.jsx` if that's okay! 

do we have a perfect example for a converted file, unit test, and PR we can look at? I already see the activity on [`ts-migrate-helper-plugin`](https://github.com/strapi/strapi/tree/chore/ts-migrate-helper-plugin), but what is the best to look at? 👀

**Comment by dallasclark** [comment]
Can I please have:
* Link.jsx
* LinkButton.jsx
* NoMedia.jsx
* NotAllowedInput.jsx

**Comment by markkaylor** [comment]
@bogdaaamn I think currently the best resource for a good example is still the Strapi Design System:

https://github.com/strapi/strapi/issues/17690#issuecomment-1683532152

**Comment by mkcy3** [comment]
Table.jsx

Both of my previous requests are approved.

**Comment by Tegacreatives** [comment]
I'd love to work on Form.jsx

**Comment by BorysShulyak** [comment]
@markkaylor Hi! Could you assign the following methods on me, please? 
- `once.js`
- `setHexOpacity.js`

**Comment by BorysShulyak** [comment]
Took in progress the following files:
- once.js
- prefixPluginTranslations.js
- prefixFileUrlWithBackendUrl.js

**Comment by Tegacreatives** [comment]
Assign setHexOpacity.js to me

**Comment by fletch-r** [comment]
Sorry didn't know I was meant to leave a comment on here.

Can my merged PR's be assigned to me:

- awaitToJs
- getFileExtension
- getPrefixedId
- setHexOpacity
- getAttributeInfos
- AppInfo

**Comment by joshuaellis** [comment]
I'll take a look at `Notifications` & `Tracking` 👍🏼

**Comment by markkaylor** [comment]
Hi @jbhammon we need to move forward with `useFetchClient`. Since we haven't seen a PR from you yet we are going to move forward and handle this one internally. If you started work somewhere feel free to share as soon as possible and we will be sure to either review and merge or add you as a co-author on an internal PR. Thanks for being willing to help out!

**Comment by simotae14** [comment]
I'll take a look at `SearchURLQuery`

**Comment by jbhammon** [comment]
> Hi @jbhammon we need to move forward with `useFetchClient`. Since we haven't seen a PR from you yet we are going to move forward and handle this one internally.

All good, life got a bit busy so I don't want to hold things up. I'll see if I can help out with other tasks soon!

**Comment by joshuaellis** [comment]
I'll take a look at InjectionZone 👍🏼

**Comment by JuliusGudni** [comment]
I would be willing to do these (if still needed):
PaginationURLQuery.jsx
ReactSelect.jsx
RelativeTime.jsx

**Comment by JuliusGudni** [comment]
I'll take formatContentTypeData too while I'm at it.

**Comment by markkaylor** [comment]
Thanks everyone for contributing! We really appreciated all the help 🎈
