### ISSUE TITLE
Tracking Issue: Fix Frontend Tests

### ISSUE THREAD

**Issue by christiancp100** [strapi/strapi#17924]
# Context
Currently, there are some failing and inconsistent tests on the front end that need to be fixed and refactored. In this issue, we want to track the process of fixing all the tests that have `console.error`, even though the tests are passing, and identify if the different tests suits contain useful tests that we should keep and identify tests that are incomplete or not fully testing the feature. 

**This is an internal activity so community contributions will not be considered**, but thanks for the interest

If you'd like to work on any of these test suits, please add yourself to the list right after the test file and once you are done, submit a PR with [this target branch](https://github.com/strapi/strapi/tree/fix/failing-frontend-tests)

BTW: If you can, while refactoring, use screen instead of render and replace the existing render instances as discussed in: https://www.notion.so/strapi/f0ed431a49b34fb38904842bec612768?v=6002999a58cf4f23becfc288d8bd3178&p=8fd5acfdcc514f43b5ed7c29f05ac085&pm=s

## packages/core/content-type-builder
- [ ]  packages/core/content-type-builder/admin/src/components/IconPicker/tests/index.test.js
- [ ]  packages/core/content-type-builder/admin/src/pages/ListView/tests/index.test.js

## packages/core/admin
- [x]  packages/core/admin/admin/src/content-manager/components/DynamicZone/tests/index.test.js **@christiancp100** 
- [x]  packages/core/admin/admin/src/content-manager/components/InputUID/tests/index.test.js @joshuaellis 
- [x]  packages/core/admin/admin/src/content-manager/components/RelationInput/components/tests/Option.test.js @joshuaellis 
- [ ]  packages/core/admin/admin/src/content-manager/components/Wysiwyg/tests/index.test.js @joshuaellis
- [x]  packages/core/admin/admin/src/content-manager/hooks/useLazyComponents/tests/useLazyComponents.test.js @joshuaellis 
- [x]  packages/core/admin/admin/src/content-manager/hooks/useRelation/tests/useRelation.test.js @joshuaellis 
- [ ]  packages/core/admin/admin/src/content-manager/pages/EditSettingsView/tests/index.test.js @joshuaellis
- [ ]  packages/core/admin/admin/src/content-manager/pages/ListSettingsView/tests/index.test.js @joshuaellis 
- [ ]  packages/core/admin/admin/src/content-manager/pages/ListView/components/BulkActionButtons/ConfirmBulkActionDialog/tests/index.test.js
- [ ]  packages/core/admin/admin/src/content-manager/pages/ListView/components/BulkActionButtons/SelectedEntriesModal/tests/index.test.js
- [ ]  packages/core/admin/admin/src/hooks/useAdminRolePermissions @joshuaellis 
- [ ]  packages/core/admin/admin/src/pages/Admin/Onboarding/tests/index.test.js
- [ ]  packages/core/admin/admin/src/pages/AuthPage/components/Login/tests/BaseLogin.test.js
- [ ]  packages/core/admin/admin/src/pages/AuthPage/components/Oops/tests/index.test.js
- [ ]  packages/core/admin/admin/src/pages/AuthPage/components/Register/tests/index.test.js
- [ ]  packages/core/admin/admin/src/pages/AuthPage/components/ResetPassword/tests/index.test.js
- [x]  packages/core/admin/admin/src/pages/MarketplacePage/tests/index.test.js @joshuaellis 
- [x]  packages/core/admin/admin/src/pages/MarketplacePage/tests/providers.test.js @joshuaellis 
- [ ]  packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/tests/index.test.js
- [ ]  packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/ListView/tests/index.test.js
- [ ]  packages/core/admin/admin/src/pages/SettingsPage/pages/TransferTokens/EditView/tests/index.test.js
- [ ] packages/core/admin/admin/src/pages/SettingsPage/pages/Webhooks/EditView/components/WebhookForm/tests/index.test.js
- [ ]  packages/core/admin/admin/src/tests/StrapiApp.test.js

## packages/core/upload
- [x]  packages/core/upload/admin/src/components/Breadcrumbs @joshuaellis 
- [x]  packages/core/upload/admin/src/components/TableList/tests/TableRows.test.js @joshuaellis 
- [x]  packages/core/upload/admin/src/hooks/tests/useConfig.test.js @joshuaellis 
- [x]  packages/core/upload/admin/src/hooks/tests/useFolders.test.js @joshuaellis 
- [x]  packages/core/upload/admin/src/hooks/tests/useModalQueryParams.test.js @joshuaellis 
- [x]  packages/core/upload/admin/src/pages/App/ConfigureTheView/tests/ConfigureTheView.test.js @joshuaellis 
- [x]  packages/core/upload/admin/src/pages/App/MediaLibrary/tests/MediaLibrary.test.js @joshuaellis 

## packages/plugins
- [x]  packages/plugins/users-permissions/admin/src/pages/Roles/pages/tests/CreatePage.test.js @joshuaellis 
- [x]  packages/plugins/users-permissions/admin/src/pages/Roles/pages/tests/EditPage.test.js @joshuaellis
